import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api } from "../api.js";
import LogoutBar from "../components/LogoutBar.jsx";

// Real templates, sourced + compiled from AyushDas4890/CV_TEMPLATES (cv-formats/).
// Thumbnails live in public/template-previews/, generated by compiling each
// template's actual .tex and rendering page 1 to PNG — these are real renders,
// not mockups. Source LaTeX for each lives in cv-templates/<id>/ at the repo root.
const TEMPLATES = [
  { id: "jake", name: "Jake's Resume" },
  { id: "dphang", name: "dphang CV" },
  { id: "anubhav", name: "Resume by Anubhav" },
  { id: "altacv", name: "AltaCV" },
  { id: "moderncv", name: "ModernCV" },
  { id: "plushcv", name: "PlushCV" },
  { id: "deedy", name: "Deedy CV" },
  { id: "awesome-cv", name: "Awesome CV" },
];

export default function TemplatePage() {
  const [previewing, setPreviewing] = useState(null); // template shown in modal, or null
  const [chosen, setChosen] = useState(null); // confirmed selection
  const [username, setUsername] = useState("");
  const [pageCounts, setPageCounts] = useState({}); // { [templateId]: number }
  const navigate = useNavigate();

  useEffect(() => {
    // reachable directly by URL, so guard it — bounce to login if no session
    api.me()
      .then((res) => setUsername(res.githubUsername))
      .catch(() => navigate("/auth"));

    // Static asset, not an authenticated call — plain fetch, not api.js.
    // Failure just means every template falls back to page-count 1 (today's behavior).
    fetch("/template-previews/manifest.json")
      .then((res) => (res.ok ? res.json() : {}))
      .then(setPageCounts)
      .catch(() => setPageCounts({}));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function pageCountFor(id) {
    return pageCounts[id] || 1;
  }

  function confirmSelection() {
    setChosen(previewing.id);
    setPreviewing(null);
    // NOTE: selection is only kept in local state right now — Ayush said
    // what to do with it (send to writer service, persist, etc.) is TBD.
  }

  return (
    <div className="shell">
      <LogoutBar username={username} />
      <div className="step-indicator">
        <span>1. Account</span>
        <span>2. Experience</span>
        <span>3. GitHub</span>
        <span className="active">4. Template</span>
      </div>
      <h1>Choose a CV template</h1>
      <p className="sub">Click a template to preview the full CV before selecting.</p>

      <div className="template-grid">
        {TEMPLATES.map((t) => (
          <div
            key={t.id}
            className={`template-card ${chosen === t.id ? "chosen" : ""}`}
            onClick={() => setPreviewing(t)}
          >
            {chosen === t.id && <span className="chosen-badge">Selected</span>}
            {pageCountFor(t.id) > 1 && (
              <span className="page-count-badge">{pageCountFor(t.id)}p</span>
            )}
            <div className="thumb">
              <img src={`/template-previews/${t.id}.png`} alt={t.name} />
            </div>
            <div className="label">{t.name}</div>
          </div>
        ))}
      </div>

      <div className="row">
        <button className="primary" disabled={!chosen}>
          Continue {chosen ? `(${TEMPLATES.find((t) => t.id === chosen).name})` : ""}
        </button>
      </div>
      {!chosen && <p className="notice">pick a template above to continue</p>}

      {previewing && (
        <div className="modal-backdrop" onClick={() => setPreviewing(null)}>
          <div className="modal-box" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h2>{previewing.name}</h2>
              <button className="modal-close" onClick={() => setPreviewing(null)}>×</button>
            </div>
            <div className="modal-body">
              <img src={`/template-previews/${previewing.id}.png`} alt={previewing.name} />
            </div>
            <div className="modal-footer">
              <button className="secondary" onClick={() => setPreviewing(null)}>Cancel</button>
              <button className="primary" onClick={confirmSelection}>Select this template</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
